# https://github.com/google-github-actions/example-workflows/blob/main/workflows/deploy-cloudrun/cloudrun-docker.yml

name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build 
    outputs:
      affected-project: ${{ steps.affected.outputs.affected_project }}
    permissions:
      contents: 'read'
      actions: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Setup node'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
            
      - run: npx nx workspace-lint
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --configuration=ci
      - run: npx nx affected --target=build --type=apps --parallel=3
      
      - id: affected
        name: Check if dockerizable backend is affected
        run: echo affected_project=$(npx nx print-affected --target=docker-build --select=projects --exclude=client) >> $GITHUB_OUTPUT  

  deploy:
    runs-on: ubuntu-latest
    name: deploy
    needs: build
    if: ${{ needs.build.outputs.affected-project == 'backend' }}
    permissions:
      contents: 'read'
      actions: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Setup node'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: npx nx affected --target=docker-build --tag=europe-west1-docker.pkg.dev/advance-proton-376516/my-repo/backend:${{ github.sha }}
     
       
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/103668507909/locations/global/workloadIdentityPools/github/providers/github-github'
          service_account: 'github-actions@advance-proton-376516.iam.gserviceaccount.com'

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: 'europe-west1-docker.pkg.dev'

      - name: Build and Push Container
        run: docker push "europe-west1-docker.pkg.dev/advance-proton-376516/my-repo/backend:${{ github.sha }}"

      - id: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v1'
        with:
          secrets: |-
            database-url:advance-proton-376516/database-url

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy backend \
          --region europe-west1 \
          --image europe-west1-docker.pkg.dev/advance-proton-376516/my-repo/backend:${{ github.sha }} \
          --platform=managed \
          --service-account=${{ secrets.SERVICE_ACCOUNT }} \
          --update-secrets=DATABASE_URL=${{ steps.secrets.outputs.database-url }} \
          --max-instances=1 \
          --add-cloudsql-instances=${{ secrets.INSTANCE_CO }} \
          --allow-unauthenticated \
          --quiet      


